name: CI/CD 
on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: cd ${github.workspace}
      - run: cmake -S ${github.workspace}/build/ -B ${github.workspace}/build/
      - run: make -C ${github.workspace}/build/